### ISSUE TITLE
Implementation darf nicht erweitert werden, sondern auf eine Implementierung muss delegiert werden.

### ISSUE THREAD

**Issue by argh87** [Ockenheimer/Gaesteliste#1]
https://github.com/Ockenheimer/Gaesteliste/blob/b06c037eae124344cb8094351fd3aa40668d205f/src/klassen/Gaesteliste.java#L16

In der verlinkten Zeile sollte List<Gast> implementiert werden und die Methoden auf ein Attribut vom Typ ArrayList<Gast> weitergeleitet werden. Das verhindert mögliche Fehler bei Updaten der Java Implementierung von ArrayList.

**Comment by Ockenheimer** [comment]
tldr :*
